### ISSUE TITLE
Windows machine unable to handle some filenames when cloning Wiki repository

### ISSUE THREAD

**Issue by michael-kricheldorf** [FLARE-forecast/flare-forecast.github.io#10]
When trying to clone the Wiki page for this repo using:
`git clone https://github.com/FLARE-forecast/flare-forecast.github.io.wiki.git`

I receive the following output in Powershell:
```
Cloning into 'flare-forecast.github.io.wiki'...
remote: Enumerating objects: 1057, done.
remote: Total 1057 (delta 0), reused 0 (delta 0), pack-reused 1057
Receiving objects: 100% (1057/1057), 220.50 KiB | 3.02 MiB/s, done.
Resolving deltas: 100% (644/644), done.
error: unable to create file Build-a-"compound-trigger"-action-in-Openwhisk.md: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

After some troubleshooting and Googling around, I found out the likely cause of the issue is that [Windows has a longer list of forbidden filename characters](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file) and that some of the files in the Wiki repo contain these forbidden characters. In the code chunk above, the file `Build-a-"compound-trigger"-action-in-Openwhisk.md` uses quotation marks.

**Comment by vahid-dan** [comment]
A wiki page had a double quotation mark (") in the filename, and when cloning, it tried to create a .md file with the same name. The Windows file system cannot handle filenames with double quotation marks. Hence, the error. It is resolved by removing the double quotation marks from the page name.
